"""
`atomic-forge fix <github_issue_url>` — one-shot issue → PR.

Pipeline (CIE required, not optional):
  1. preflight: LLM env present + CIE importable, else bail with a clear message.
  2. parse the issue URL; fetch the issue title + body (the bug description).
  3. get a runnable checkout: shallow-clone the repo (or use --project-dir),
     gitignore tool artifacts (.cie/.venv/.forge), stand up a venv + install.
  4. populate CIE: `cie index` the checkout, serve CIE as an MCP server.
  5. CIE generates a regression test from the issue (grounded in the real
     signatures via graph tools); validate it reproduces the bug (fails on
     the buggy code on an assertion). Abort if it can't reproduce — no PR.
  6. forge's repair loop (CIE-backed) fixes the bug against that test,
     re-running it each round until green or --max-rounds.
  7. on green: fork the repo, push the fix branch to the FORK only (never to
     origin), open a PR `fork → upstream`. --dry-run skips the push/PR.

CIE is mandatory here. The repair loop itself is unchanged; this orchestrator
just wires CIE-MCP + test-gen + the fork-only PR around it.
"""
from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path
from typing import Optional

from .agent import render_tool_manifest
from .cie_backend import MCPBridge, MCPToolBackend, cie_index, require_cie
from .issue import (clone_repo, fetch_issue, issue_to_bug_description,
                    make_test_cmd, parse_issue_url, setup_python_env, upstream_slug)
from .llm import OpenAICompatLLM
from .pr import default_branch_for, prepare_pr_branch, raise_pr_via_fork
from .repair_agent import repair_loop_agentic
from .testgen import generate_regression_test, oracle_fails_on_buggy
from .trajectory import Trajectory

def _ground_truth_green(project_dir: Path, test_cmd: str, timeout: int = 300) -> bool:
    """Re-run the generated test ourselves and trust that, not the repair
    loop's self-report."""
    chk = subprocess.run(test_cmd, shell=True, cwd=str(project_dir),
                         capture_output=True, text=True, timeout=timeout)
    return chk.returncode == 0


_IGNORE_ARTIFACTS = [".cie/", ".venv/", ".forge/"]


def _gitignore_artifacts(project_dir: Path) -> None:
    """Append .cie/ .venv/ .forge/ to the checkout's .gitignore so the
    repair loop's `git add -A` (in sandbox.commit) doesn't stage the CIE
    graph DB / venv / forge state into the PR."""
    gi = project_dir / ".gitignore"
    existing = gi.read_text() if gi.exists() else ""
    add = [line for line in _IGNORE_ARTIFACTS if line not in existing]
    if add:
        with gi.open("a") as f:
            if existing and not existing.endswith("\n"):
                f.write("\n")
            f.write("\n".join(add) + "\n")


def _pr_title(issue: dict, override: Optional[str]) -> str:
    if override:
        return override
    title = (issue.get("title") or "bug").strip().splitlines()[0][:80]
    return f"fix(issue #{issue['number']}): {title}"


def _pr_body(issue: dict, report: dict, test_rel: str) -> str:
    repo_bit = f"{issue['owner']}/{issue['repo']}#{issue['number']}"
    return (
        f"Fixes {issue.get('url') or repo_bit}\n\n"
        "## What\n"
        f"autonomous fix via `atomic-forge fix` — CIE (code graph over MCP) "
        "localized the bug, generated a failing regression test, and forge's "
        "repair loop fixed the source against it.\n\n"
        f"## Issue\n> **{issue.get('title','').strip()}**\n\n"
        f"{(issue.get('body','') or '').strip()[:2000]}\n\n"
        "## How it was verified\n"
        f"- regression test: `{test_rel}` (CIE-generated; fails on the pre-fix "
        "code, passes on the fix)\n"
        f"- repair rounds: {report.get('rounds')}  "
        f"failures: {report.get('initial_failures')} -> {report.get('final_failures')}\n"
        f"- repaired file(s): {', '.join(report.get('repaired_files', [])) or 'n/a'}\n\n"
        "_Generated by `atomic-forge fix <issue-url>`._\n"
    )


def run_fix(url: str, llm: OpenAICompatLLM, *,
            project_dir: Optional[Path] = None,
            install_cmd: Optional[str] = None,
            max_rounds: int = 5, max_turns: int = 10,
            dry_run: bool = False,
            pr_base: Optional[str] = None, pr_branch: Optional[str] = None,
            pr_title: Optional[str] = None,
            issue_body_file: Optional[Path] = None,
            work_root: Optional[Path] = None,
            samples: int = 2, max_turns_per_attempt: int = 25) -> dict:
    """Run the full fix pipeline. Returns a report dict (always; includes
    `success`, `stage`, and either `pr_url` or `reason` on failure)."""
    require_cie()
    owner, repo, number = parse_issue_url(url)
    upstream = upstream_slug(owner, repo)

    # 2. issue
    if issue_body_file:
        body_text = Path(issue_body_file).read_text()
        issue = {"title": Path(issue_body_file).stem, "body": body_text,
                 "url": url, "number": number, "owner": owner, "repo": repo}
        print(f"[forge fix] using issue body from {issue_body_file}")
    else:
        print(f"[forge fix] fetching issue {upstream}#{number}")
        issue = fetch_issue(owner, repo, number)
    bug = issue_to_bug_description(issue)

    # 3. checkout
    if project_dir is None:
        work_root = Path(work_root or (Path(tempfile.gettempdir()) / "forge_fix"))
        project_dir = work_root / f"{repo}-{number}"
        print(f"[forge fix] cloning {upstream} -> {project_dir}")
        clone_repo(owner, repo, project_dir)
    project_dir = Path(project_dir)
    _gitignore_artifacts(project_dir)
    print(f"[forge fix] setting up venv + installing project (this can take a bit)")
    venv_py = setup_python_env(project_dir, install_cmd=install_cmd)

    # branch for the fix (commits from the repair loop land here, not on default)
    branch = pr_branch or f"forge/fix-issue-{number}"
    prepare_pr_branch(project_dir, branch)
    print(f"[forge fix] on branch {branch}")

    # 4. CIE index + MCP server
    db = project_dir / ".cie" / "graph.db"
    print(f"[forge fix] indexing code graph with CIE ...")
    cie_index(project_dir, db)
    bridge = MCPBridge(project_dir, db)
    backend = MCPToolBackend(bridge, project_dir)
    manifest = backend.describe()["results"]
    manifest_text = render_tool_manifest(manifest)

    traj = Trajectory(project_dir)
    test_rel = f"tests/test_forge_issue_{number}.py"
    (project_dir / "tests").mkdir(exist_ok=True)

    result = {"url": url, "upstream": upstream, "issue_number": number,
              "branch": branch, "test_file": test_rel, "success": False}
    try:
        # 5. CIE generates a regression test that reproduces the bug
        print(f"[forge fix] CIE generating regression test at {test_rel} ...")
        gen = generate_regression_test(llm, bridge, project_dir, test_rel, bug, max_turns=max_turns)
        result["testgen_turns"] = gen["turns"]
        if not gen["generated"].strip():
            result.update(stage="testgen", reason="CIE produced no test file")
            print("[forge fix] abort: no regression test generated; no PR raised.")
            return result
        fails, out = oracle_fails_on_buggy(project_dir, test_rel, venv_py)
        result["test_reproduces_bug"] = fails
        if not fails:
            result.update(stage="validate", reason="generated test does not reproduce the bug "
                          "(passes on buggy code or has a collection error)")
            print("[forge fix] abort: the generated test does not reproduce the bug; no PR raised.")
            print(f"  pytest output tail:\n" + "\n".join(out.splitlines()[-8:]))
            return result
        print("[forge fix] generated test reproduces the bug — entering repair loop.")

        # 6. forge repair loop (CIE-backed) against the generated test
        test_cmd = make_test_cmd(venv_py, test_rel)
        print(f"[forge fix] repair loop (max_rounds={max_rounds}, test={test_rel}) ...")
        report = repair_loop_agentic(
            project_dir, llm, backend, traj, test_cmd=test_cmd,
            max_rounds=max_rounds, samples=samples,
            max_turns_per_attempt=max_turns_per_attempt,
            timeout=300, tool_manifest=manifest, tool_manifest_text=manifest_text,
            tasks_by_file={})
        result["repair"] = {
            "success": report.get("success"), "rounds": report.get("rounds"),
            "initial_failures": report.get("initial_failures"),
            "final_failures": report.get("final_failures"),
            "repaired_files": report.get("repaired_files", []),
        }

        # ground-truth re-check of the generated test (don't trust self-report)
        green = _ground_truth_green(project_dir, test_cmd)
        result["ground_truth_green"] = green
        if not green:
            result.update(stage="repair", reason="repair did not make the generated test pass")
            print("[forge fix] repair exhausted; the generated test still fails; no PR raised.")
            return result
        result["success"] = True
        result["stage"] = "fixed"

        # 7. fork-only PR (never push to origin)
        title = _pr_title(issue, pr_title)
        body = _pr_body(issue, result["repair"], test_rel)
        base = pr_base or default_branch_for(upstream)
        if dry_run:
            r = raise_pr_via_fork(project_dir, upstream=upstream, title=title, body=body,
                                  base=base, dry_run=True)
            result.update(stage="dry_run", pr_url=None, dry_run=r)
            print(f"[forge fix] dry-run: fix ready on branch {branch} (base {base}); "
                  f"NOT pushing / NOT opening a PR.")
        else:
            print(f"[forge fix] bug fixed — forking {upstream} and opening a PR ...")
            r = raise_pr_via_fork(project_dir, upstream=upstream, title=title, body=body, base=base)
            result["pr_url"] = r.get("pr_url")
            result["fork"] = r.get("fork")
            print(f"[forge fix] PR opened: {r.get('pr_url')}  (fork -> {upstream}, base {base})")
        return result
    finally:
        bridge.stop()
        usage = getattr(llm, "usage", None)
        if usage:
            print(f"[forge fix] {usage.summary()}")
        print(f"[forge fix] trajectory: {traj.path}")