"""
QA phase: cover every dev task with a real, runnable test file.

- If the batch already contains explicit 'qa' tasks, those are generated by
  the normal generator (they're just tasks like any other).
- For every 'dev' task with a test_triad and no explicit qa task depending
  on it, this module synthesizes a minimal qa AtomicTask straight from the
  triad and hands it to the SAME generator every other file goes through
  (`generate_agent.generate_file_agentic`) — one canonical generator, no
  separate one-shot test-writing code path to keep in sync.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

from .llm import ChatLLM
from .models import AtomicTask, AtomicTaskBatch
from .tools import ToolBackend
from .trajectory import Trajectory


def qa_target_for(task: AtomicTask) -> str:
    """Test file path for a dev task's gap-fill QA: mirrors the source
    file's directory under `tests/`."""
    p = Path(task.file_path)
    safe = re.sub(r"[^A-Za-z0-9_]", "_", task.name)
    if p.suffix in (".ts", ".tsx", ".js", ".jsx"):
        return str(Path("tests") / p.parent / f"{p.stem}.test{p.suffix}")
    return str(Path("tests") / p.parent / f"test_{safe}.py")


def _ensure_conftest(project_dir: Path) -> None:
    tests_dir = project_dir / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    conftest = tests_dir / "conftest.py"
    if not conftest.exists():
        conftest.write_text(
            "import sys\nfrom pathlib import Path\n"
            "sys.path.insert(0, str(Path(__file__).resolve().parent.parent))\n"
        )


def _synthesize_qa_task(task: AtomicTask) -> AtomicTask:
    """Build a qa AtomicTask directly from `task`'s own test_triad — no
    separate mining step. The test_triad IS the spec; this just wraps it
    into the same AtomicTask contract the generator already understands."""
    triad = task.test_triad
    assert triad is not None
    target = qa_target_for(task)
    steps = [
        f"Import the real code under test from {task.file_path!r} — never fake or reimplement it.",
        f"Positive case: {triad.positive}",
        f"Negative case: {triad.negative}",
        f"Negative-to-positive (recovery) case: {triad.negative_to_positive}",
        "Use the test framework this project's other test files already use (infer from any "
        "sibling test file you can view; otherwise the ecosystem default for this file's language).",
        "Mock external services/network/filesystem where appropriate; never depend on real "
        "network access or a real external database in a unit test.",
    ]
    return AtomicTask(
        name=f"{task.name} (tests)",
        userstory_id=task.userstory_id,
        parent_feature=task.parent_feature,
        task_type="qa",
        layer=task.layer,
        action="create",
        file_path=target,
        description=f"Test file covering {task.file_path} per its test_triad.",
        function_signatures=[],
        step_by_step_implementation=steps,
        dependencies=[task.file_path],
    )


def generate_missing_qa_files(project_dir, tasks: list[AtomicTask], llm: ChatLLM,
                               tools: ToolBackend, traj: Trajectory,
                               reporter=None, tool_manifest_text: str = "",
                               tool_manifest: Optional[list] = None) -> list[Path]:
    """Cover a batch of dev tasks with no explicit QA task by synthesizing
    one qa AtomicTask per task (straight from its test_triad) and running
    each through the normal generator. Returns the file(s) written — []
    if nothing in `tasks` qualifies."""
    project_dir = Path(project_dir)
    from .generate_agent import generate_file_agentic

    qualifying: list[AtomicTask] = []
    for task in tasks:
        if task.task_type != "dev" or task.test_triad is None:
            continue
        if not (project_dir / task.file_path).exists():
            traj.log("qa", file=task.file_path, result="skipped-missing-source")
            continue
        qualifying.append(task)
    if not qualifying:
        return []

    _ensure_conftest(project_dir)

    written: list[Path] = []
    for task in qualifying:
        synth = _synthesize_qa_task(task)
        target = generate_file_agentic(
            project_dir, synth, llm, tools, traj,
            reporter=reporter, tool_manifest_text=tool_manifest_text, tool_manifest=tool_manifest,
        )
        written.append(target)
        traj.log("qa", file=synth.file_path, for_task=task.name, result="synthesized+generated")
    return written


def qa_phase(project_dir, batch: AtomicTaskBatch, llm: ChatLLM, tools: ToolBackend,
             traj: Trajectory, reporter=None,
             tool_manifest_text: str = "", tool_manifest: Optional[list] = None,
             already_covered: "set[str] | None" = None) -> list[Path]:
    """Generate tests for dev tasks not already covered by an explicit qa
    task. `already_covered`: file_paths whose gap-fill QA already ran
    elsewhere, so this pass acts purely as a safety net."""
    covered = set(already_covered) if already_covered else set()
    for qa_task in batch.qa_tasks():
        for dep in qa_task.dependencies:
            covered.add(dep)

    needs_qa = [t for t in batch.dev_tasks() if t.file_path not in covered]
    written = generate_missing_qa_files(
        project_dir, needs_qa, llm, tools, traj,
        reporter=reporter, tool_manifest_text=tool_manifest_text, tool_manifest=tool_manifest,
    )
    if reporter is not None:
        for path in written:
            reporter.artifact("qa_phase", str(Path(path).relative_to(Path(project_dir))), "test")
    return written
